### ISSUE TITLE
How to control systemd daemons and services?

### ISSUE THREAD

**Issue by AliSawari** [systemd/python-systemd#102]
I was looking for a systemd wrapper in python and I came across this awesome tool, but there is no clear documentation for controlling daemons and services (starting , restarting, stopping, enabling, disabling ). is there any way to do this? or it is yet to be implemented?
Judging from the source code, this is a native API to the systemd with C, if this is the case it should be completely doable.
any ideas?

**Comment by AliSawari** [comment]
update: 
there is a way to connect and use systemd via python, which is the native systemd API exposed on the Dbus interface
[here is a link](https://wiki.freedesktop.org/www/Software/systemd/dbus/)

it would be much nicer to be implemented in this package

**Comment by keszybz** [comment]
For that, use https://github.com/facebookincubator/pystemd instead.
