### ISSUE TITLE
SystemError: incompatible with python 3.10

### ISSUE THREAD

**Issue by TitaniumHocker** [systemd/python-systemd#107]
When using package with python3.10 this error occurs on using `systemd.journal.Reader`:
```
...
reader.this_boot()
  File "/home/ifedorov/.cache/pypoetry/virtualenvs/jviewer-g9vQZSG3-py3.10/lib/python3.10/site-packages/systemd/journal.py", line 376, in this_boot
    self.add_match(_BOOT_ID=bootid)
  File "/home/ifedorov/.cache/pypoetry/virtualenvs/jviewer-g9vQZSG3-py3.10/lib/python3.10/site-packages/systemd/journal.py", line 244, in add_match
    super(Reader, self).add_match(arg)
SystemError: PY_SSIZE_T_CLEAN macro must be defined for '#' formats
```
See: https://docs.python.org/3/c-api/arg.html#strings-and-buffers
See: https://docs.python.org/3/whatsnew/3.10.html#id2

This error seems to be fixed in [this](https://github.com/systemd/python-systemd/commit/c71bbac357f0ac722e1bcb2edfa925b68cca23c9) commit, so new release needs to be made.

**Comment by kylemanna** [comment]
Just ran in to this as well, would love to see a new release tagged with the fix incorporated.

**Comment by keszybz** [comment]
Yeah, this will be fixed in the next release.
