### ISSUE TITLE
journal.sendv() should be consistent about raising exceptions on arguments

### ISSUE THREAD

**Issue by mulkieran** [systemd/python-systemd#11]
```
>>> journal.__version__
'216'
>>> journal.sendv('GRAPH=graph')
>>> journal.sendv('MESSAGE=graph')
```

The first sendv silently fails, the second silently succeeds (I guess sendv won't succeed unless the MESSAGE field is set.) Also...

```
>>> graph = 'graph\n'
>>> journal.sendv('GRAPH=%s' % graph)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IOError: [Errno 90] Message too long
>>> journal.sendv('GRAPH=%s' % graph, 'MESSAGE=actually, not too long')
```
In the above, IOError, Message too long, is raised. But, if I include the message field, it is logged to the journal.

```
Oct 29 11:47:24 localhost.localdomain python[20979]: actually, not too long
Oct 29 11:44:35 localhost.localdomain python[20979]: graph
```

So, some false assumptions are being made in error handling code which are pretty confusing too the user.

Note that in 219 the behavior is mostly the same, except that 'Message too long' become 'Invalid...'.

```
>>> journal.sendv('GRAPH=%s' % graph)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IOError: [Errno 22] Invalid argument
```

This is a good  change, because it doesn't seem to be the length of the message that is the problem, just the fact that it contains a newline. But it is still wrong that the message is raised at all.

So, the two problems are:
1) It should be possible to tell whether sendv has succeeded or failed, but it currently isn't.
2) Error reporting should be better. Since a newline in a field is not actually a problem, the errors shown above should not be reported.

**Comment by mulkieran** [comment]
Ok. So the problem is not as bad as I thought. The entry is being logged to the journal, but it is not shown when the journal is displayed using journalctl with the default output format because there is no message. This is good. It is possible that journalctl is doing the wrong thing, but that is a separate issue.

So the problem really is that all the writes above should be succeeding but some of them don't OR that some of the writes that include fields with line breaks in them should be causing an exception to be raised, but aren't.

AFAICT, the only time when the exception is raised is when the the key with the field with a line break is the only argument to sendv().

```
[mulhern@localhost pyblk]$ python
Python 2.7.8 (default, Jul  5 2015, 14:16:16) 
[GCC 4.9.2 20150212 (Red Hat 4.9.2-6)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from systemd import journal
>>> journal.sendv('MESSAGE_ID=94a9ab0126ed438ebbc99b9771841f22')
>>> journal.sendv('MESSAGE_ID=94a9ab0126ed438ebbc99b9771841f22', 'GRAPH=ab\n')
>>> journal.sendv('GRAPH=ab\n')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IOError: [Errno 90] Message too long
>>> journal.sendv('MESSAGE_ID=94a9ab0126ed438ebbc99b9771841f22', 'GRAPH=ab\nd')
```

and

```
[mulhern@localhost pyblk]$ journalctl --reverse MESSAGE_ID=94a9ab0126ed438ebbc99b9771841f22
-- Logs begin at Thu 2013-09-26 07:51:58 EDT, end at Fri 2015-10-30 13:17:04 EDT
```

but

```
[mulhern@localhost pyblk]$ journalctl --reverse MESSAGE_ID=94a9ab0126ed438ebbc99b9771841f22 --output=verbose | wc -l
73
```

**Comment by keszybz** [comment]
Journal allows entries without MESSAGE. There has been some discussion of disallowing this, but no patches were proposed afaik.

The erratic errors you saw were because of libsystemd problems. They should be now fixed in systemd/systemd@13bd195053f6ce1c1adfff514c5c6ba79e53c913.

Please reopen if you still observe problems with the updated systemd.

**Comment by mulkieran** [comment]
OK, thanks!

For the record, I'm in favor of allowing log entries w/ no MESSAGE field, just not in favor of journalctl skipping them when requested output is one of the terser formats.

**Comment by keszybz** [comment]
But how would you display them then?

**Comment by mulkieran** [comment]
The same way you display ones w/ a MESSAGE field that is an empty string. Those do get displayed by journalctl if they match the filter, regardless of the format chosen.

**Comment by keszybz** [comment]
I don't see what the benefit to the user would be. Journal entries without MESSAGE would be very confusing in majority of uses. And on the other hand, I don't see a usecase that would be served by MESSAGES-less entries.

**Comment by mulkieran** [comment]
There are a couple of things going on:
1. The display format shouldn't change whether a log entry is filtered out or not, but it does. If journalctl is going to omit displaying a log entry because it has no MESSAGE field, then it should be consistent across all formats. The smart way, IMO, is to always display the entry, rather than to never display the entry. I feel that that's the smart way, because even with the terse formats, a fair amount of information is still displayed even when there is no MESSAGE field set. With the more verbose formats, a ton of stuff is displayed.
2. The journal has a notion of catalog, which you know about. With the catalog it actually does start to make sense to have an entry without a MESSAGE field and the expectation that the information would be filled in by means of the catalog. In fact, a MESSAGE-less entry would be in the spirit of journal's new structured format, trending away from the older approaches to the journal of only logging free form messages. Require a MESSAGE entry always and you'll get the same kind of goofiness that you get with emails, where people put "SSIA (Subject Says it All)" in the body of the email just to get it past their mailer, and so forth.
