### ISSUE TITLE
Start, Stop, Restart services examples?

### ISSUE THREAD

**Issue by Jzarecta** [systemd/python-systemd#13]
Would be nice to see some documentation on starting, restarting and check status on the services on the README. 
Looking at the man pages, it seems I should be using the service handler, but I would like to see some code example.

**Comment by keszybz** [comment]
There is nothing in python-systemd that is used to do anything with services. You'd do that over dus, and python-systemd only wraps the C api. This could change at some point in the future, but currently there's nothing to document, because there's no functionality like that.
