### ISSUE TITLE
RHEL/CentOS 7 support on PyPI

### ISSUE THREAD

**Issue by mikenerone** [systemd/python-systemd#29]
I need this library on CentOS 7 using Python 3 from http://ius.io/ . As mentioned in #5, the current package on PyPI, i.e. the recent `systemd-python==232`, doesn't work on CentOS 7. `from systemd import journal` fails with `undefined symbol: sd_journal_open_files_fd`. (On a side note, I'm a bit confused as this project's README states that it's already packaged for Python 3 in the official RHEL/CentOS repos, but I can't find any sign of that, or even Python 3 itself).

As RHEL/CentOS are major distributions and represent a big chunk of people, I'd like to request that a compatible version of systemd-python be pushed to PyPI. Perhaps the support for `sd_journal_open_files_fd` can be made backward-compatible. Or maybe it would be necessary to push up an older build.

**Comment by keszybz** [comment]
I now pushed 233 to pypi.
