### ISSUE TITLE
systemd/id128.c:149:29: fatal error: id128-constants.h: No such file or directory

### ISSUE THREAD

**Issue by gtmanfred** [systemd/python-systemd#3]
```
systemd/id128.c: In function ‘PyInit_id128’:
systemd/id128.c:149:29: fatal error: id128-constants.h: No such file or directory
compilation terminated.
error: command 'gcc' failed with exit status 1
==> ERROR: A failure occurred in build().
    Aborting...
```

This is fixed in the master, but needs a new tagged release to fix it.

Thanks
Daniel

**Comment by skorokithakis** [comment]
This isn't fixed in master for me, I'm seeing this when building.

**Comment by afterdesign** [comment]
This is fixed as a hack in Makefile:

```
systemd/id128-constants.h: $(INCLUDE_DIR)/systemd/sd-messages.h
	$(SED) -n -r 's/,//g; s/#define (SD_MESSAGE_[A-Z0-9_]+)\s.*/add_id(m, "\1", \1) JOINER/p' <$< >$@

build: systemd/id128-constants.h
	$(PYTHON) setup.py build
```

**Comment by gtmanfred** [comment]
I am dumb, i should have just added the `make systemd/id128-constants.h` before the python setup.py build.

thanks @afterdesign

**Comment by afterdesign** [comment]
@gtmanfred is this hack really necessary ?

**Comment by gtmanfred** [comment]
it isn't needed, you can just run the make on the systemd/id128-constants.h
directly before running python setup.py build.

Turns out someone had already packaged it on arch, and is just building
from a git commit

On Mon, Aug 24, 2015 at 12:49 PM, Rafał Malinowski <notifications@github.com
