### ISSUE TITLE
Can't filter using "_SYSTEMD_UNIT"

### ISSUE THREAD

**Issue by cryzed** [systemd/python-systemd#36]
I want to monitor the journal of a running vpn-client unit. To do so I first used `sudo journalctl -f --output=json` to get an idea of the general structure of each entry's catalog (unimportant information truncated):

```json
{
  "SYSLOG_IDENTIFIER" : "openvpn",
  "_COMM" : "openvpn",
  "_EXE" : "/usr/bin/openvpn",
  "_CMDLINE" : "/usr/sbin/openvpn --suppress-timestamps --nobind --config VPN.conf",
  "_SYSTEMD_CGROUP" : "/system.slice/system-openvpn\\x2dclient.slice/openvpn-client@VPN.service",
  "_SYSTEMD_UNIT" : "openvpn-client@VPN.service",
  "_SYSTEMD_SLICE" : "system-openvpn\\x2dclient.slice",
  "MESSAGE" : "...",
  "_PID" : "4586"
}
```

Based on this, I figured I could use `.add_match(_SYSTEMD_UNIT='openvpn-client@VPN.service')` [as documented](https://www.freedesktop.org/software/systemd/python-systemd/journal.html#systemd.journal.Reader) to get access to the corresponding journal.

However I can't seem to fetch and journal entries when doing so:

```python
reader = systemd.journal.Reader()
reader.this_boot()
reader.add_match(_SYSTEMD_UNIT='openvpn-client@VPN.service')
for entry in reader:
    print(entry)
```

Will simply print nothing, while confusingly (to me) specifying the `SYSLOG_IDENTIFIER` instead will work:

```python
reader = systemd.journal.Reader()
reader.this_boot()
reader.add_match(SYSLOG_IDENTIFIER='openvpn')
for entry in reader:
    print(entry)
```

However this fetches the entries of all openvpn journals, which I don't want. I also made sure using `journalctl --boot --unit openvpn-client@VPN.service` that journal entries matching the specified filter exist. (Removing the `this_boot()`-filter also doesn't lead to any entries being fetched).

Any advice?

**Comment by keszybz** [comment]
I run your script with
```
  reader.add_match('_SYSTEMD_UNIT=user@1000.service')
```
and 
```
  reader.add_match(_SYSTEMD_UNIT='user@1000.service')
```
and I get a bunch of entries with both. I don't have use openvpn, but your script seems to work OK.

You should check if you get the expected entries with `journalctl`. Your script corresponds to `journalctl -b _SYSTEMD_UNIT=openvpn-client@VPN.service -o json`, and if that gives you entries, but the script doesn't, something is very wrong.

**Comment by keszybz** [comment]
Closing because of lack of feedback. Please reopen if needed.
