### ISSUE TITLE
dict.iteritems() doesn't exist in Python 3

### ISSUE THREAD

**Issue by joell** [systemd/python-systemd#41]
A [recent change](https://github.com/systemd/python-systemd/blob/master/systemd/journal.py#L562) to `JournalHandler.emit` uses the Python 2.x `iteritems()` method of `dict`, but this method no longer exists in Python 3.x.

**Comment by joell** [comment]
This issue would be completely resolved by accepting pull request #39 .

**Comment by keszybz** [comment]
Fixed in dce0a85.

@joell thanks for the fix. In the future, please add "Fixed #blah", so that github will autoclose the issue when the commit is applied.
