### ISSUE TITLE
Cannot install on CentOS 7

### ISSUE THREAD

**Issue by dvska** [systemd/python-systemd#47]
**Linux 3.10.0-327.36.3.el7.x86_64**
**Python 3.5.2 (default, Jun 27 2016, 14:02:55)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-4)] on linux
systemd 219**

----

$ dnf install python3-systemd

  Using metadata from Thu Apr 13 14:55:29 2017
  No package python3-systemd available.
 Error: no package matched: python3-systemd

----
$ dnf install python-systemd

 Using metadata from Thu Apr 13 14:55:29 2017
 No package python-systemd available.
 Error: no package matched: python-systemd

----

$ pip3 install git+https://github.com/systemd/python-systemd.git#egg=systemd

  Collecting systemd from git+https://github.com/systemd/python-systemd.git#egg=systemd
  Cloning https://github.com/systemd/python-systemd.git to /tmp/pip-build-13uuw3rj/systemd
    Complete output from command python setup.py egg_info:
    Cannot find libsystemd or libsystemd-journal:

    Package libsystemd was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libsystemd.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libsystemd' found

    Package libsystemd-journal was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libsystemd-journal.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libsystemd-journal' found
    ----------------------------------------

----

$ pip install systemd-python
Collecting systemd-python
  Using cached systemd-python-234.tar.gz
    Complete output from command python setup.py egg_info:
    Cannot find libsystemd or libsystemd-journal:

    Package libsystemd was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libsystemd.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libsystemd' found

    Package libsystemd-journal was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libsystemd-journal.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libsystemd-journal' found

**Comment by keszybz** [comment]
Try installing systemd-devel first (with dnf).

**Comment by dvska** [comment]
Hi Zbigniew ,
Please add the `dnf install systemd-devel` to README
