### ISSUE TITLE
poll and fileno()

### ISSUE THREAD

**Issue by hholst80** [systemd/python-systemd#48]
I have a loop which seems to work for some time but then after a number of messages it starts to fall through even there is no data available on the Reader.

Basically, 

```
j = journal.Reader()
j.this_boot()
poller = select.poll()
poller.register(j.fileno())
while True:
    poller.poll()  # returns within 1E-6 seconds
    print(j.get_next())  # prints out {}
```

Is this some fundamental use error on my side? The poller object should only return when the journal endpoint has some data to be read?

I have systemd-python version:

```
In [6]: systemd.journal.__version__
Out[6]: '234'
```

**Comment by anikey-m** [comment]
Found solution of same problem on https://stackoverflow.com/questions/26331116/reading-systemd-journal-from-python-script. They described in detail the reasons for this behavior and gave documentation references. In short: you should use `Reader.process()` after poll call.

I hope this helps someone.

**Comment by alex-bender** [comment]
@anikey-m Thanks for providing links!
Indeed documentation should be improved for that.
