### ISSUE TITLE
Update python-systemd releases to PyPi

### ISSUE THREAD

**Issue by Ormod** [systemd/python-systemd#5]
It would be great if the python-systemd releases were uploaded to pypi promptly, allowing pip install of it.

**Comment by afterdesign** [comment]
huge :+1: on this

**Comment by kmrs** [comment]
Same here, would be really nice to install it with pip!

**Comment by itamarst** [comment]
While that would be great (e.g. for automatic dependencies in other packages), so please do this, note that one can as a workaround `pip install https://github.com/systemd/python-systemd/archive/v230.tar.gz`.

**Comment by keszybz** [comment]
Hm, python-system on pypi is a completely unrelated project. I could reach out to them, but I doubt that they would want to change the name, or if it makes sense at all, since it could lead to even more confusion.

**Comment by mulkieran** [comment]
pyjournalctl is, I think, the name of the completely obsoleted version of this project on pypi. Maybe it would be OK to update that instead. It would be nice for me, since I do CI using tox in travis, and my current strategy is to skip all python-systemd tests and checks. I'ld rather not, but I have yet to figure out how to make anything better work (see https://github.com/mulkieran/pyblk/commit/8b8c208cf8be33ffb1aebe0c64e35cedb74e9cd5).

**Comment by OptiverTimAll** [comment]
`python-systemd` on PyPI (version 0.0.9) is indeed unrelated to this package.

It would still be great to have this package available on PyPI somewhere, though, even under a different name (like "systemd", or "pysystemd") so it can easily be deployed into a virtualenv.

**Comment by keszybz** [comment]
Hm, I uploaded https://pypi.python.org/pypi/systemd-python/232 now, but `pip install --user systemd-python` does not work. I don't understand why. `pip install --user https://pypi.python.org/packages/87/a3/e73a8373d40b05a75bb34fdccae606ab4dc0c0743535289904f15eb624f5/systemd-python-232.tar.gz` seems to work without any issue.

**Comment by OptiverTimAll** [comment]
I ran `pip install systemd-python` in a virtualenv and it downloaded, built and installed just fine. It didn't actually work, because systemd-python 232 requires a newer version of libsystemd than CentOS 7 provides, but it built and installed just fine.

**Comment by Frzk** [comment]
@keszybz : Works for me too. That's great, thanks a lot ! 👍

**Comment by keszybz** [comment]
OK, closing than. Thanks for testing.
