### ISSUE TITLE
test_notify_socket fails when ran from within nspawn

### ISSUE THREAD

**Issue by ignatenkobrain** [systemd/python-systemd#50]
mock uses nspawn and build fails on

```python
____________________________ test_notify_no_socket _____________________________

    def test_notify_no_socket():
>       assert notify('READY=1') is False
E       OSError: [Errno 13] Permission denied

systemd/test/test_daemon.py:260: OSError
```

With @torsava we were not able to debug it, so filing report here.. =(

**Comment by keszybz** [comment]
Fedora mock now uses nspawn by default and the package builds fine, so I guess that the is got resolved. In normal systemd-nspawn this doesn't happen either. Let's close.
