### ISSUE TITLE
Systemd version on Semaphore CI is still 204

### ISSUE THREAD

**Issue by MarcelWaldvogel** [systemd/python-systemd#61]
(Also) providing a newer version would allow testing
- `sd_pid_notify`
- `sd_pid_notify_with_fds`
- `sd_is_socket_sockaddr`
- `sd_listen_fds_with_names`

**Comment by keszybz** [comment]
Yeah. I could easily upgrade to 16.04 in semaphore, but then the testing on old versions would be lost. I test the latest systemd locally, so it makes sense to test with the oldest version in CI. So to fix this properly, testing with multiple versions would be nice.

**Comment by MarcelWaldvogel** [comment]
Yes, multiple versions would indeed be the way to go. Not knowing Semaphore myself, I do not know how much time this takes to set up.

**Comment by keszybz** [comment]
If you want to work on this, I'd be happy to give you privileges on the python-systemd semaphore repo.

**Comment by MarcelWaldvogel** [comment]
Too generous. I doubt I will be able to find the time in the next few months.

**Comment by keszybz** [comment]
semaphore is no more.
