### ISSUE TITLE
C90 compatibility is only enforced in the CI

### ISSUE THREAD

**Issue by MarcelWaldvogel** [systemd/python-systemd#62]
Running `make` or `make check` on the local system does not complain about C99 constructs (such as defining the loop variable in the loop itself, e.g. 2596c5d).

This makes it hard to create code which passes CI.

Can this be changed in the Makefile? Or can the requirement to be C90 compatible be relaxed?

**Comment by Frank-Krick** [comment]
I think you should be able to achieve that by adding '--std=c90' to the extra_compile_args of the constructor for the Extension objects in setup.py.

**Comment by Frank-Krick** [comment]
Yes, I agree. Unfortunately the maintainers are very quiet here.

I just came to see if the documentation was updated regarding systemd-activate -> systemd-socket-activate, which you already did in one of your commits.
