### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by Glandos** [systemd/python-systemd#68]
Sorry for this fake issue.

But I need to know (and maybe I'm not alone) if this project is still maintained, or not. It can also be in standby. We just don't know what's happening, because there are some opened pull requests for more than one year without any comments.

Once again, sorry for pinging @keszybz but you seems to be the last active contributor to this, so maybe you can answer this.

**Comment by h5rdly** [comment]
I am looking for a systemd wrapper to use in my project myself, joining the query. 
There seems to be another wrapper named cysystemd -
 
https://github.com/mosquito/cysystemd
Last update on February, Apache license.

**Comment by keszybz** [comment]
Yeah, this project is still alive (mostly). libsystemd provides very good backwards compatiblity, so it doesn't really "break" if it's not updated for a while, but of course new features are not added, etc. Co-maintainers are welcome.
