### ISSUE TITLE
RFE: provide service status querying

### ISSUE THREAD

**Issue by TurboTurtle** [systemd/python-systemd#73]
Are there any plans for this project to support querying service status from systemd? Or for that matter, controlling services via start/stop/restart requests (provided permissions are sufficient of course)?

For example, I'd like to be able to do something like the following:

```python
from systemd import Service

svc = Service('my-cool-service')
status = svc.status()  # similar content to running 'systemctl status my-cool-service'
if svc.is_active():
    ... do stuff...
else:
    svc.start()
```

**Comment by keszybz** [comment]
For that, use https://github.com/facebookincubator/pystemd instead.
