### ISSUE TITLE
JournalHandler: set journald unit

### ISSUE THREAD

**Issue by FedericoCeratto** [systemd/python-systemd#74]
Daemons need to be able to generate logs with the same unit name configured in the systemd unit file.
JournalHandler should provide a way to do so and document it as as recommended pattern.

**Comment by Phibonacci** [comment]
This can be done with:
```py
JournalHandler(SYSLOG_IDENTIFIER="unit_name")
```

**Comment by frq-asgard-fake** [comment]
`SYSLOG_IDENTIFIER` sets the syslog identifier not the unit name. Specifically filtering with `journalctl -u $name` is not possibly according to my tests. Am I missing something or is the example just wrong?
