### ISSUE TITLE
Cannot install on CentOS 7

### ISSUE THREAD

**Issue by drgrumpy** [systemd/python-systemd#78]
Tried:
`dnf install python-systemd python3-systemd`

result:
Error: Unable to find a match: python-systemd python3-systemd

and: 
```
sudo pip3 install git+https://github.com/systemd/python-systemd.git#egg=systemd
Traceback (most recent call last):
  File "/bin/pip3", line 16, in <module>
    sys.exit(main())
TypeError: 'module' object is not callable
```

**Comment by jvoosten** [comment]
Same here; CentOS 7, just says "unable to find a match". Apparently this modules is not packaged for one of the most popular operating systems, or there are some additions steps required.
