### ISSUE TITLE
Administrative operation with python binding

### ISSUE THREAD

**Issue by GreatBahram** [systemd/python-systemd#82]
Hello there,

How can I do the administrative operations with this binding? For instance, `logrotate`, or other things that `journalctl` can do like `vacuum-size` or `vacuum-time`?

Thanks

**Comment by keszybz** [comment]
Those are done over dbus, which this module doesn't support at all. https://github.com/facebookincubator/pystemd is more appropriate.

**Comment by GreatBahram** [comment]
Thanks
