### ISSUE TITLE
Logs between two dates

### ISSUE THREAD

**Issue by GreatBahram** [systemd/python-systemd#83]
Hello there,

I want to get logs only between two specific dates, how should I achieve that?

Thanks

**Comment by GreatBahram** [comment]
@keszybz do you have any idea?

**Comment by keszybz** [comment]
It is described in the [manual](http://www.freedesktop.org/software/systemd/man/journalctl.html). See the `--since` and `--until` options.

**Comment by GreatBahram** [comment]
I was asking about the python binding, not `journalctl`. 
By the way, I found the information by reading the journalctl's source code. I think you guys should work on the documentation. It is really hard for someone who tries to use this binding. Adding just a couple of examples about retrieving logs would be sensational.

**Comment by keszybz** [comment]
Ah, sorry, I didn't look at the URL.
