### ISSUE TITLE
How to get the start and end date of journal files in Python?

### ISSUE THREAD

**Issue by GreatBahram** [systemd/python-systemd#84]
Hello there,
I was reading the [`journalctl`](https://github.com/systemd/systemd/blob/09f87228011cb763c3c0a94193d3f4eb0c6cc23b/src/journal/journalctl.c#L2560) source code and realized there is this `sd_journal_get_cutoff_realtime_usec` which provides the start and end date of journal files, How can I get that result in Python?

**Comment by GreatBahram** [comment]
Any suggestion?

**Comment by keszybz** [comment]
Fixed by #92.
