### ISSUE TITLE
Latest release is too old

### ISSUE THREAD

**Issue by alexole** [systemd/python-systemd#99]
Hello,

Could you please make a new release? It's been awhile since the last one.
I am in a need of this functionality which was added quite some time ago https://github.com/systemd/python-systemd/pull/87

Thanks!

**Comment by keszybz** [comment]
Yeah.

**Comment by kloczek** [comment]
+1

**Comment by mbiebl** [comment]
> Yeah.

Hi @keszybz, any updates here?

**Comment by mbiebl** [comment]
Duplicate of  #76.
We should close one of the two.
